"""Recommendation API endpoints.

Provides portfolio health recommendations generated by
the Smart Funnel pipeline (pre-filter, gap analysis,
LLM reasoning).  Results are cached in Redis with
per-user scoped keys.
"""

import logging

from fastapi import (
    APIRouter,
    Depends,
    HTTPException,
    Query,
    Response,
)

from auth.dependencies import get_current_user
from auth.models import UserContext
from cache import TTL_STABLE, get_cache
from recommendation_models import (
    AggregateStats,
    HistoryRunItem,
    RecommendationHistoryResponse,
    RecommendationItem,
    RecommendationResponse,
    RecommendationStatsResponse,
)

_logger = logging.getLogger(__name__)


def _set_cache_header(response: Response):
    """Router dependency: Cache-Control on all."""
    yield
    response.headers["Cache-Control"] = (
        "private, max-age=60"
    )


def _get_session_factory():
    """Return the PG async session factory."""
    from backend.db.engine import get_session_factory

    return get_session_factory()


def _build_rec_item(d: dict) -> RecommendationItem:
    """Map a PG dict to a Pydantic rec item."""
    tags = d.get("index_tags") or []
    acted = d.get("acted_on_date")
    if acted and hasattr(acted, "isoformat"):
        acted = acted.isoformat()
    return RecommendationItem(
        id=str(d.get("id", "")),
        tier=d.get("tier", ""),
        category=d.get("category", ""),
        ticker=d.get("ticker"),
        company_name=d.get("company_name"),
        action=d.get("action", ""),
        severity=d.get("severity", ""),
        rationale=d.get("rationale", ""),
        expected_impact=d.get("expected_impact"),
        data_signals=d.get("data_signals", {}),
        price_at_rec=d.get("price_at_rec"),
        target_price=d.get("target_price"),
        expected_return_pct=d.get(
            "expected_return_pct",
        ),
        index_tags=tags if tags else [],
        status=d.get("status", "active"),
        acted_on_date=str(acted) if acted else None,
    )


def _build_run_response(
    run: dict,
    recs: list[dict],
) -> RecommendationResponse:
    """Assemble a full run response."""
    run_date = run.get("run_date", "")
    if hasattr(run_date, "isoformat"):
        run_date = run_date.isoformat()
    created = run.get("created_at")
    if created and hasattr(created, "isoformat"):
        created = created.isoformat()
    return RecommendationResponse(
        run_id=str(run.get("run_id", "")),
        run_date=str(run_date),
        run_type=run.get("run_type", ""),
        health_score=float(
            run.get("health_score", 0),
        ),
        health_label=run.get(
            "health_label", "unknown",
        ),
        health_assessment=run.get(
            "health_assessment",
        ),
        recommendations=[
            _build_rec_item(r) for r in recs
        ],
        generated_at=str(created) if created else None,
        cached=bool(run.get("was_cached", False)),
        reset_at=run.get("reset_at"),
        scope=run.get("scope"),
    )


def create_recommendation_router() -> APIRouter:
    """Build the recommendations sub-router."""
    router = APIRouter(
        prefix="/dashboard/portfolio/recommendations",
        tags=["recommendations"],
        dependencies=[Depends(_set_cache_header)],
    )

    # --------------------------------------------------
    # GET / — latest recommendation set
    # --------------------------------------------------
    @router.get(
        "",
        response_model=RecommendationResponse,
    )
    async def get_latest(
        market: str = Query(
            "all",
            description="all|india|us",
        ),
        user: UserContext = Depends(
            get_current_user,
        ),
    ):
        """Return latest recommendation run."""
        cache = get_cache()
        ck = (
            f"cache:portfolio:recs"
            f":{user.user_id}:{market}"
        )
        hit = cache.get(ck)
        if hit is not None:
            return Response(
                content=hit,
                media_type="application/json",
            )

        from backend.db.pg_stocks import (
            get_latest_recommendation_run,
            get_recommendations_for_run,
        )

        factory = _get_session_factory()
        async with factory() as session:
            run = (
                await get_latest_recommendation_run(
                    session,
                    str(user.user_id),
                    scope=market,
                )
            )
        if not run:
            return RecommendationResponse(
                run_id="",
                run_date="",
                run_type="",
                health_score=0,
                health_label="no_data",
                recommendations=[],
            )

        async with factory() as session:
            recs = (
                await get_recommendations_for_run(
                    session, run["run_id"],
                )
            )

        # Filter by market if not "all"
        if market != "all":
            from market_utils import detect_market

            recs = [
                r
                for r in recs
                if not r.get("ticker")
                or detect_market(r["ticker"])
                == market
            ]

        resp = _build_run_response(run, recs)
        body = resp.model_dump_json()
        cache.set(ck, body, TTL_STABLE)
        return Response(
            content=body,
            media_type="application/json",
        )

    # --------------------------------------------------
    # POST /refresh — trigger manual Smart Funnel run
    # --------------------------------------------------
    @router.post(
        "/refresh",
        response_model=RecommendationResponse,
    )
    async def refresh(
        market: str = Query(
            "india",
            description="india|us|all",
        ),
        user: UserContext = Depends(
            get_current_user,
        ),
    ):
        """Trigger (or reuse) a Smart Funnel run.

        Rule: one run per user per scope per IST
        calendar month.  If a run already exists for
        the current month, the existing run is
        returned unchanged.  ``market=all`` expands
        to two runs (``india`` + ``us``); the first
        non-empty result is returned as the primary
        response.
        """
        import asyncio

        from jobs.recommendation_engine import (
            get_or_create_monthly_run,
        )

        uid = str(user.user_id)

        scopes = (
            ["india", "us"] if market == "all"
            else [market]
        )
        for s in scopes:
            if s not in ("india", "us"):
                raise HTTPException(
                    status_code=400,
                    detail=(
                        f"Invalid scope '{s}'. "
                        "Use 'india', 'us', or 'all'."
                    ),
                )

        def _call(scope_val: str) -> dict:
            return get_or_create_monthly_run(
                uid, scope_val,
                run_type="manual",
            )

        results: list[dict] = []
        for s in scopes:
            results.append(
                await asyncio.to_thread(_call, s),
            )

        cache = get_cache()
        cache.invalidate(
            f"cache:portfolio:recs:{uid}:*",
        )

        # Pick the primary result: first with a run_id
        primary = next(
            (r for r in results if r.get("run_id")),
            results[0] if results else {},
        )
        if not primary.get("run_id"):
            note = primary.get(
                "status_note", "no_recommendations",
            )
            raise HTTPException(
                status_code=422,
                detail=(
                    "Could not generate "
                    f"recommendations ({note})."
                ),
            )

        recs = primary.get("recommendations", [])
        resp = _build_run_response(primary, recs)
        return Response(
            content=resp.model_dump_json(),
            media_type="application/json",
        )

    # --------------------------------------------------
    # GET /history — past runs with outcomes
    # --------------------------------------------------
    @router.get(
        "/history",
        response_model=(
            RecommendationHistoryResponse
        ),
    )
    async def get_history(
        months_back: int = Query(
            6, ge=1, le=24,
        ),
        user: UserContext = Depends(
            get_current_user,
        ),
    ):
        """Return past runs with rec counts."""
        from backend.db.pg_stocks import (
            get_recommendation_history,
            get_recommendation_stats,
        )

        factory = _get_session_factory()
        uid = str(user.user_id)

        async with factory() as session:
            rows = (
                await get_recommendation_history(
                    session, uid, months_back,
                )
            )
        async with factory() as session:
            stats = await get_recommendation_stats(
                session, uid,
            )

        run_items = []
        for r in rows:
            # Use created_at (has time) over run_date
            rd = r.get("created_at") or r.get(
                "run_date", "",
            )
            if hasattr(rd, "isoformat"):
                rd = rd.isoformat()
            run_items.append(
                HistoryRunItem(
                    run_id=str(
                        r.get("run_id", ""),
                    ),
                    run_date=str(rd),
                    scope=r.get("scope", "all"),
                    run_type=r.get(
                        "run_type", "scheduled",
                    ),
                    health_score=float(
                        r.get("health_score", 0),
                    ),
                    health_label=r.get(
                        "health_label", "unknown",
                    ),
                    total_recommendations=r.get(
                        "rec_count", 0,
                    ),
                    acted_on_count=int(
                        r.get("acted_on_count", 0)
                    ),
                )
            )

        total_recs_agg = stats.get("total_recs", 0) or 0
        total_acted_agg = (
            stats.get("total_acted_on", 0) or 0
        )
        adoption_pct = (
            round(
                total_acted_agg / total_recs_agg * 100,
                1,
            )
            if total_recs_agg
            else 0.0
        )
        agg = AggregateStats(
            total_runs=stats.get(
                "total_runs", 0,
            ),
            total_recommendations=total_recs_agg,
            overall_avg_return_pct=stats.get(
                "avg_return_pct",
            ),
            overall_avg_excess_pct=stats.get(
                "avg_excess_return_pct",
            ),
            adoption_rate_pct=adoption_pct,
        )

        resp = RecommendationHistoryResponse(
            runs=run_items,
            aggregate_stats=agg,
        )
        return Response(
            content=resp.model_dump_json(),
            media_type="application/json",
        )

    # --------------------------------------------------
    # GET /stats — aggregate performance stats
    # --------------------------------------------------
    @router.get(
        "/stats",
        response_model=(
            RecommendationStatsResponse
        ),
    )
    async def get_stats(
        scope: str = Query(
            "all",
            description="all|india|us",
        ),
        user: UserContext = Depends(
            get_current_user,
        ),
    ):
        """Return aggregate recommendation stats.

        When *scope* is ``india`` or ``us``, the stats
        are filtered to that scope so the page's
        scope-filtered view shows a matching adoption
        rate.  Default ``all`` keeps the historical
        cross-scope total.
        """
        from backend.db.pg_stocks import (
            get_recommendation_stats,
        )

        factory = _get_session_factory()
        uid = str(user.user_id)

        async with factory() as session:
            stats = await get_recommendation_stats(
                session, uid,
                scope=(
                    scope if scope in ("india", "us")
                    else None
                ),
            )

        total_recs = stats.get("total_recs", 0)
        total_acted_on = stats.get(
            "total_acted_on", 0,
        )
        hit_rate = stats.get("hit_rate_pct")

        resp = RecommendationStatsResponse(
            total_recommendations=total_recs,
            total_acted_on=total_acted_on,
            adoption_rate_pct=(
                round(
                    total_acted_on
                    / total_recs
                    * 100,
                    1,
                )
                if total_recs
                else 0.0
            ),
            hit_rate_30d=hit_rate,
            avg_return_30d=stats.get(
                "avg_return_pct",
            ),
            avg_excess_return_30d=stats.get(
                "avg_excess_return_pct",
            ),
        )
        return Response(
            content=resp.model_dump_json(),
            media_type="application/json",
        )

    # --------------------------------------------------
    # GET /{run_id} — specific run details
    # --------------------------------------------------
    @router.get(
        "/{run_id}",
        response_model=RecommendationResponse,
    )
    async def get_run(
        run_id: str,
        user: UserContext = Depends(
            get_current_user,
        ),
    ):
        """Return a specific recommendation run."""
        from backend.db.pg_stocks import (
            get_recommendations_for_run,
        )
        from sqlalchemy import select

        factory = _get_session_factory()

        # Verify run belongs to user
        from backend.db.models.recommendation import (
            RecommendationRun,
        )

        async with factory() as session:
            result = await session.execute(
                select(RecommendationRun).where(
                    RecommendationRun.run_id
                    == run_id,
                    RecommendationRun.user_id
                    == str(user.user_id),
                )
            )
            run_row = result.scalar_one_or_none()

        if not run_row:
            raise HTTPException(
                status_code=404,
                detail="Run not found.",
            )

        # Convert ORM to dict
        from backend.db.pg_stocks import (
            _rec_run_to_dict,
        )

        run = _rec_run_to_dict(run_row)

        async with factory() as session:
            recs = (
                await get_recommendations_for_run(
                    session, run_id,
                )
            )

        resp = _build_run_response(run, recs)
        return Response(
            content=resp.model_dump_json(),
            media_type="application/json",
        )

    return router
