import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Resolved at build time so the URL bakes into the
// HTML — no runtime cost. Falls back to the dev
// default; deployed builds pull from the env.
const BACKEND_URL =
  process.env.NEXT_PUBLIC_BACKEND_URL ??
  "http://localhost:8181";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Open the connection to the backend ahead
            of the first XHR/fetch — saves the DNS
            lookup + TLS handshake (≈100-200 ms) on
            every authenticated route load. Both
            preconnect and dns-prefetch are emitted
            because legacy browsers honour only the
            latter. */}
        <link
          rel="preconnect"
          href={BACKEND_URL}
          crossOrigin="anonymous"
        />
        <link rel="dns-prefetch" href={BACKEND_URL} />
        {/* Prevent FOUC: apply dark class before React hydrates */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{var t=localStorage.getItem("theme");if(t==="dark"||(t!=="light"&&matchMedia("(prefers-color-scheme:dark)").matches))document.documentElement.classList.add("dark")}catch(e){}})()`,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
