"""Tests for ``load_ohlcv_window`` (Task 7.10 — epoch floor).

Verifies that the SQL generated by ``load_ohlcv_window`` includes the
``date >= '1980-01-01'`` epoch floor added in Task 7.10 (CLAUDE.md
§6.5 pre-1980 corrupt-epoch-date defence).
"""
from __future__ import annotations

from datetime import date
from unittest.mock import patch

from backend.algo.backtest.data_source import load_ohlcv_window

_MODULE = "backend.algo.backtest.data_source"


class TestLoadOhlcvWindowEpochFloor:
    """SQL-assertion tests — no catalog I/O required."""

    def test_sql_contains_epoch_floor(self):
        """Generated SQL must contain ``date >= '1980-01-01'``.

        Monkeypatches ``query_iceberg_table`` to capture the SQL
        string without hitting the catalog.
        """
        captured_sql: list[str] = []

        def _capture(table, sql, params):
            captured_sql.append(sql)
            return []

        with patch(
            f"{_MODULE}.query_iceberg_table", side_effect=_capture,
        ):
            load_ohlcv_window(
                tickers=["ITC.NS"],
                period_start=date(2025, 1, 1),
                period_end=date(2025, 12, 31),
            )

        assert captured_sql, "query_iceberg_table was never called"
        assert "1980-01-01" in captured_sql[0], (
            "load_ohlcv_window SQL must include date >= '1980-01-01' "
            "epoch floor (CLAUDE.md §6.5)"
        )

    def test_epoch_floor_present_with_warmup_days(self):
        """Epoch floor is in SQL even when ``warmup_days`` widens the
        window (the BETWEEN param may go before 1980, the literal
        guard must still appear)."""
        captured_sql: list[str] = []

        def _capture(table, sql, params):
            captured_sql.append(sql)
            return []

        with patch(
            f"{_MODULE}.query_iceberg_table", side_effect=_capture,
        ):
            load_ohlcv_window(
                tickers=["TCS.NS"],
                period_start=date(2025, 6, 1),
                period_end=date(2025, 6, 30),
                warmup_days=60,
            )

        assert "1980-01-01" in captured_sql[0], (
            "epoch floor must appear even when warmup_days extends "
            "effective_start"
        )
