"""initial schema — 5 tables

Revision ID: 1670e38531ce
Revises: 
Create Date: 2026-03-29 20:53:41.922794
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1670e38531ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_jobs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('cron_days', sa.String(length=200), nullable=True),
    sa.Column('cron_time', sa.String(length=10), nullable=True),
    sa.Column('cron_dates', sa.String(length=200), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stock_registry',
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('last_fetch_date', sa.Date(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('date_range_start', sa.Date(), nullable=True),
    sa.Column('date_range_end', sa.Date(), nullable=True),
    sa.Column('market', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_index(op.f('ix_stock_registry_last_fetch_date'), 'stock_registry', ['last_fetch_date'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_sub', sa.String(length=255), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('page_permissions', sa.String(length=1000), nullable=True),
    sa.Column('subscription_tier', sa.String(length=50), nullable=True),
    sa.Column('subscription_status', sa.String(length=50), nullable=True),
    sa.Column('razorpay_customer_id', sa.String(length=255), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('monthly_usage_count', sa.Integer(), nullable=True),
    sa.Column('usage_month', sa.String(length=7), nullable=True),
    sa.Column('subscription_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('subscription_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_user_oauth', 'users', ['oauth_provider', 'oauth_sub'], unique=False)
    op.create_index('ix_user_tier', 'users', ['subscription_tier'], unique=False)
    op.create_table('payment_transactions',
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('gateway', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('gateway_event_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_id', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('tier_before', sa.String(length=50), nullable=True),
    sa.Column('tier_after', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('raw_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index('ix_payment_gateway_event', 'payment_transactions', ['gateway', 'gateway_event_id'], unique=False)
    op.create_table('user_tickers',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='manual', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'ticker')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tickers')
    op.drop_index('ix_payment_gateway_event', table_name='payment_transactions')
    op.drop_table('payment_transactions')
    op.drop_index('ix_user_tier', table_name='users')
    op.drop_index('ix_user_oauth', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stock_registry_last_fetch_date'), table_name='stock_registry')
    op.drop_table('stock_registry')
    op.drop_table('scheduled_jobs')
    # ### end Alembic commands ###
