"""add pipeline tables

Revision ID: ead20959ea5b
Revises: a2f8b1c9d4e7
Create Date: 2026-04-06 20:09:18.856356
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ead20959ea5b'
down_revision: Union[str, None] = 'a2f8b1c9d4e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_cursor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cursor_name', sa.String(length=100), nullable=False),
    sa.Column('total_tickers', sa.Integer(), nullable=False),
    sa.Column('last_processed_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('batch_size', sa.Integer(), server_default='50', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cursor_name')
    )
    op.create_table('stock_master',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('yf_ticker', sa.String(length=30), nullable=False),
    sa.Column('nse_symbol', sa.String(length=30), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=5), server_default='INR', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_master_exchange'), 'stock_master', ['exchange'], unique=False)
    op.create_index(op.f('ix_stock_master_is_active'), 'stock_master', ['is_active'], unique=False)
    op.create_index(op.f('ix_stock_master_isin'), 'stock_master', ['isin'], unique=True)
    op.create_index(op.f('ix_stock_master_symbol'), 'stock_master', ['symbol'], unique=True)
    op.create_index(op.f('ix_stock_master_yf_ticker'), 'stock_master', ['yf_ticker'], unique=False)
    op.create_table('ingestion_skipped',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cursor_name', sa.String(length=100), nullable=False),
    sa.Column('ticker', sa.String(length=30), nullable=False),
    sa.Column('job_type', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('error_category', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='1', nullable=False),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cursor_name'], ['ingestion_cursor.cursor_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'tag', 'added_at', name='uq_stock_tag_added')
    )
    op.create_index(op.f('ix_stock_tags_stock_id'), 'stock_tags', ['stock_id'], unique=False)
    op.drop_index('ix_memory_embedding', table_name='user_memories', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '20'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_memory_embedding', 'user_memories', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '20'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_stock_tags_stock_id'), table_name='stock_tags')
    op.drop_table('stock_tags')
    op.drop_table('ingestion_skipped')
    op.drop_index(op.f('ix_stock_master_yf_ticker'), table_name='stock_master')
    op.drop_index(op.f('ix_stock_master_symbol'), table_name='stock_master')
    op.drop_index(op.f('ix_stock_master_isin'), table_name='stock_master')
    op.drop_index(op.f('ix_stock_master_is_active'), table_name='stock_master')
    op.drop_index(op.f('ix_stock_master_exchange'), table_name='stock_master')
    op.drop_table('stock_master')
    op.drop_table('ingestion_cursor')
    # ### end Alembic commands ###
